/*
 * alzui-mini 演示程序模板库
 */
runtime.regTpl("test_win", {
"pane_main.xml":"<div _align=\"client\" _layout=\"BorderLayout\"><ul id=\"left1\" class=\"mui-ListBox pane-left\" _align=\"left\"><!--\n\t\t<li _id=\"home\"><a href=\"index.html\">介绍</a></li>\n\t--></ul><div id=\"main1\" class=\"pane-main\" _align=\"client\"></div></div>",
"pane_home.xml":"<div class=\"pane\"><div style=\"margin:10px;\"><h5>概要</h5><p>目前还没有任何内容，仅仅演示了加载框架代码的语法。</p><h5>控制台组件</h5><p>主要供开发调试时使用</p><h5>Window组件</h5><h5>Table组件</h5></div></div>",
"pane_console.xml":"<div class=\"pane\"></div>",
"pane_window.xml":"<div class=\"pane\"><div id=\"win1\" class=\"mui-Window-winxp\" _icon=\"images/win-icon.gif\" _caption=\"窗体组件标题栏 - Windown XP\"><div class=\"body\"><input type=\"checkbox\" checked=\"checked\" /><label>resizable</label><br /><textarea id=\"ta\" rows=\"6\" cols=\"60\"></textarea></div></div><div id=\"win2\" class=\"mui-Window-win2k\" _icon=\"images/win-icon.gif\" _caption=\"窗体组件标题栏 - Windown 2000\"><div class=\"body\"><input type=\"checkbox\" checked=\"checked\" /><label>resizable</label><p>这是一个Window组件的Demo，刚刚加到UI组件库中，想把它做成一个能够支持动态换肤的Window组件。</p></div></div></div>",
"pane_table.xml":"<div class=\"pane\" title=\"表格组件\"></div>",
"pane_form.xml":"<div class=\"pane\" title=\"通用表单\"><form name=\"frm_1\" method=\"POST\" action=\"xxx.php\"><ul><li><input type=\"text\" name=\"text\" value=\"文本框\" /></li><li><input type=\"password\" name=\"password\" value=\"密码框\" /></li><li><input type=\"radio\" name=\"radio\" value=\"1\" checked=\"checked\" /> 是 <input type=\"radio\" name=\"radio\" value=\"0\" /> 否</li><li><input type=\"checkbox\" name=\"checkbox\" value=\"1\" /> 复选框</li><li><textarea name=\"textarea\" wrap=\"off\">文本区</textarea></li><li><select name=\"select\"><option value=\"0\">item0</option><option value=\"1\" selected=\"selected\">item1</option><option value=\"2\">item2</option></select></li><li><select name=\"listbox\" multiple=\"multiple\"><option value=\"0\">item0</option><option value=\"1\" selected=\"selected\">item1</option><option value=\"2\">item2</option></select></li><li><textarea name=\"textarea\" wrap=\"off\">文本区</textarea></li><li><input type=\"file\" name=\"file\" value=\"\" /> 文件选择框</li><li><input type=\"image\" name=\"image\" src=\"../res/images/win-icon.gif\" /> 图片按钮</li><li><input type=\"button\" name=\"button\" value=\"普通按钮\" /></li><li><input type=\"reset\" name=\"reset\" value=\"重置按钮\" /></li><li><input type=\"submit\" name=\"submit\" value=\"提交按钮\" /></li></ul></form></div>"
});
